export const projects = [
  {
    title: 'ResiTools',
    image: '/images/resitools.png',
    description: "ResiTools is a Chrome Extension that is aimed to be used for Residential Broadband agents at 2degrees. Features include a Time Without Service Calculator, Surcharge Calculator, and a chrome sync templates storage area for quick access to templates in a hotseating environment.",
      tags: ['Chrome Extensions', 'JavaScript', 'HTML', 'CSS'],
    visit: 'https://github.com/simseandev/resitools',
    id: 0,
  },
  {
    title: 'Assess',
    image: '/images/assess.png',
    description: "Assess is a web application designed for the University of Canterbury. In order to set-up computer rooms for exam conditions, they would run SQL queries in a command line. This application made it far easier to visualise the information and schedule exams. This group project was awarded first place with an A+ grade.",
    tags: ['PHP', 'JavaScript', 'MySQL', 'HTML', 'CSS'],
    visit: 'https://github.com/amf133/263_Assignment',
    id: 1,
  },
  {
    title: 'Petitions Front-end/Back-end',
    image: '/images/makepetitions.png',
    description: "A university project dedicated to learning about web architecture. A Petitions website which fires API requests and SQL queries to handle account authentication, photo uploading, creation and signing of petitions. Worth 70% of course, awarded A grade.",
      tags: ['Vue.js', 'Express.js', 'Node.js', 'MySQL', 'HTML', 'CSS'],
    visit: 'https://github.com/simonlorimer/SENG365-petitions-frontend-backend',
    id: 2,
  },
  {
    title: 'RIPv2 Protocol Simulator',
    image: '/images/ripv2.png',
    description:"A command line application that mimics the RIPv2 Routing Protocol. Allows you to configure text files that act as routers. The command line acts as the interface. Features include Periodic/Triggered updates and invalidation of routes. Changes show via a timer.",
    tags: ['Python'],
    visit: 'https://github.com/simonlorimer/COSC364-RIPv2-Routing',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started BSc: Computer Science Degree at UC', },
  { year: 2018, text: 'Started job as Customer Care Specialist at 2degrees', },
  { year: 2018, text: 'Attended Aspiring Leaders Forum', },
  { year: 2020, text: 'Started Assistant Web Developer internship at Contracta', },
  { year: 2021, text: 'Promoted to Senior Technical Specialist at 2degrees', },
  { year: 2021, text: 'Started Developer Internship at 2degrees', },
  { year: 2021, text: 'Graduated from UC with Computer Science degree', },
  { year: 2021, text: 'Offered permenant Software Developer position at 2degrees', },
];

export const quotes = [
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.", author: "Steve Jobs" },
  { quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
  { quote: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey" },
  { quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { quote: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { quote: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Helen Keller" },
  { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { quote: "You can't afford to think about what might have been. You just be aware of what is.", author: "Noel Gallagher" },
  { quote: "Whoever is happy will make others happy too.", author: "Anne Frank" },
  { quote: "Do what you can.", author: "Patrick Pieters" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { quote: "I failed my way to success.", author: "Thomas Edison" },
  { quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "I like criticism. It makes you strong.", author: "LeBron James" },
  { quote: "The root of suffering is attachment.", author: "Buddha" },
  { quote: "I came, I saw, I conquered.", author: "Julius Caesar" },
  { quote: "It does not matter how slowly you go so long as you do not stop.", author: "Confucius" },
  { quote: "Good artists copy, great artists steal.", author: "Pablo Picasso" },
  { quote: "Better to die standing than to live on your knees.", author: "Ernesto “Che” Guevara" },
  { quote: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { quote: "Do something worth remembering.", author: "Elvis Presley" },
  { quote: "I don’t make music for eyes. I make music for ears.", author: "Adele" },
  { quote: "Your love makes me strong. Your hate makes me unstoppable.", author: "Cristiano Ronaldo" },
  { quote: "True perfection has to be imperfect. I know that sounds foolish, but it's true.", author: "Noel Gallagher" },
]